Birja/Areas/Admin/Controllers/HomeController.cs
using FefuHobbies.Domain;
using FefuHobbies.Domain.Entities;
using FefuHobbies.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FefuHobbies.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public async Task<IActionResult> Index()
        {
            int pageSize = 20;   // количество элементов на странице
            IQueryable<Card> source = dataManager.Cards.FindCards(" ", false);
            var count = await source.CountAsync();
            var items = await source.Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, 1, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Cards = items,
                keyWords = " "
            };
            return View(viewModel);
        }
    }
}

Birja/Areas/User/Controllers/HomeController.cs
using FefuHobbies.Domain;
using FefuHobbies.Models;
using Microsoft.AspNetCore.Mvc;

namespace FefuHobbies.Areas.User.Controllers
{
    [Area("User")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            MainViewModel model = new MainViewModel();
            model.last = dataManager.Cards.GetCards().TakeLast(4);
            model.second = dataManager.Cards.GetCards().Take(4);
            return View(model);
        }
        public IActionResult About()
        {
            return View();
        }
    }
}

Birja/Controllers/CardsController.cs
using FefuHobbies.Domain;
using FefuHobbies.Domain.Entities;
using FefuHobbies.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FefuHobbies.Controllers
{
    public class CardsController : Controller
    {
        private readonly DataManager dataManager;
        public CardsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        [HttpPost]
        public async Task<IActionResult> Page(string keyWords, int page = 1)
        {
            int pageSize = 2;   // количество элементов на странице
            IQueryable<Card> source = dataManager.Cards.FindCards(keyWords, true);
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Cards = items,
                keyWords = keyWords
            };
            return View(viewModel);


        }
        public IActionResult CardView(ulong id, string kWords = null, int p = default)
        {
            /*CardViewModel entity = new CardViewModel
            {
                card = dataManager.Cards.GetCardById(id),
                keyWords=kWords,
                page = p
            };*/
            return View();
        }

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> PointsOfInterst(int page = 1)
        {
            int pageSize = 20;   // количество элементов на странице
            IQueryable<Card> source = dataManager.Cards.GetCards();
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Cards = items,
                keyWords = "Точка-интереса"
            };
            return View("Page", viewModel);
        }
        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Events(int page = 1)
        {
            int pageSize = 20;   // количество элементов на странице
            IQueryable<Card> source = dataManager.Cards.GetCards();
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Cards = items
            };
            return View("Page", viewModel);
        }

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> Last(int page = 1)
        {
            int pageSize = 20;   // количество элементов на странице
            IQueryable<Card> source = dataManager.Cards.GetCards();
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Cards = items
            };
            return View("Page", viewModel);
        }
    }
}

Birja/Controllers/HomeController.cs
using FefuHobbies.Domain.Entities;
using FefuHobbies.Domain;
using FefuHobbies.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FefuHobbies.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            MainViewModel model = new MainViewModel();
            //model.last = dataManager.Cards.Last().TakeLast(4);
            //model.second = dataManager.Cards.ByType("Точка-интереса").Take(4);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Page(string keyWords, int page = 1)
        {
            int pageSize = 2;   // количество элементов на странице
            IQueryable<Card> source = dataManager.Cards.FindCards(keyWords, true);
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Cards = items
            };
            return View(viewModel);
        }
        public IActionResult About()
        {
            return View();
        }

    }
}

Birja/Views/Home/About.cshtml
    <div class = "flex2">    
    <p>FEFU hobbies – твой лучший помощник при выборе досуга на кампусе! Благодаря этому сервису ты сможешь быстро и удобно выбрать мастер-класс, лекцию, встречу или другой вид активности по интересующему тебя направлению. На сайте собраны различные места на кампусе, где ты можешь погулять, отдохнуть или поработать. Присоединяйся к студенческим организациям, общайся с единомышленниками, расширяй кругозор и знакомься с новыми людьми. Отдыхай, учись, наслаждайся!
    </p>
    <img src="~/img/chaika.png" class = "ck" >
    </div>
    <a class = "public" asp-area="" asp-controller="home" asp-action="Index">Вернуться на главную</a>

Birja/Views/Home/Index.cshtml
<section class="search">
        <div class="s">
            <div class="container1">
                <h class="h1">
                Твоя стажировка
                </h>
                <div class="cont">
                    <button class="cont1"></button>
                    <button class="cont2">
                        <h style="font-size: 25px; color: #ffff;">
                        поиск
                        </h>
                    </button>
                </div>
            </div>

            <div class="container2">
                <div class="bloc1">
                    <button class="b1"><h style="font-size: 20px; color: #ffff;">О сервисе</hstyle=></button>
                    <button class="b2"><h style="font-size: 20px; color: #ffff;">Работадателям</h></button>
                </div>

                <button class="bloc2">
                    <h style="font-size: 20px; color: #ffff;">Раширенный поиск</h>
                </button>
            </div>
        </div>
    </section>
    <section>
        <div class="flex">
            <div>
                <h class="h3">
                    Стажировки дня
                </h>
            </div>
            <div class="conteiner">
               <ul class="cards">
                    <a class = "card" asp-area="" asp-controller="Cards" asp-action="CardView" asp-route-id="0" asp-route-retCtrl="Home" asp-route-retAcr="Index">
                    <li class="card card_tape1">
                    <h>
                        <div class="coupon">
                            <div class="container">
                              <h2>Очень крутая стажировка</h2>
                            </div>
                            <div class="container">
                                <h3 style="font-size: 20px">Крутое краткое описание</h3>
                            </div>
                            <div class="container">
                              <p class="expire"style="font-size: 20px;">от 100000 руб</p>
                            </div>
                          </div> 
                    </h>
                    </li>
                    </a>
                    <li class="card card_tape1">
                    <h>
                        <div class="coupon">
                            <div class="container">
                              <h2>Очень крутая стажировка</h2>
                            </div>
                            <div class="container">
                                <h3 style="font-size: 20px">Крутое краткое описание</h3>
                            </div>
                            <div class="container">
                              <p class="expire"style="font-size: 20px;">от 100000 руб</p>
                            </div>
                          </div> 
                    </h>
                    </li>
                    <li class="card card_tape1">
                    <h>
                        <div class="coupon">
                            <div class="container">
                              <h2>Очень крутая стажировка</h2>
                            </div>
                            <div class="container">
                                <h3 style="font-size: 20px">Крутое краткое описание</h3>
                            </div>
                            <div class="container">
                              <p class="expire"style="font-size: 20px;">от 100000 руб</p>
                            </div>
                          </div> 
                    </h>
                    </li>
                    <li class="card card_tape1">
                    <h>
                        <div class="coupon">
                            <div class="container">
                              <h2>Очень крутая стажировка</h2>
                            </div>
                            <div class="container">
                                <h3 style="font-size: 20px">Крутое краткое описание</h3>
                            </div>
                            <div class="container">
                              <p class="expire"style="font-size: 20px;">от 100000 руб</p>
                            </div>
                          </div> 
                    </h>
                    </li>
                    <li class="card card_tape1">
                    <h>
                        <div class="coupon">
                            <div class="container">
                              <h2>Очень крутая стажировка</h2>
                            </div>
                            <div class="container">
                                <h3 style="font-size: 20px">Крутое краткое описание</h3>
                            </div>
                            <div class="container">
                              <p class="expire"style="font-size: 20px;">от 100000 руб</p>
                            </div>
                          </div> 
                    </h>
                    </li>
                    <li class="card card_tape1">
                    <div class="coupon">
                        <div class="container">
                          <h2>Очень крутая стажировка</h2>
                        </div>
                        <div class="container">
                            <h3 style="font-size: 20px">Крутое краткое описание</h3>
                        </div>
                        <div class="container">
                          <p class="expire"style="font-size: 20px;">от 100000 руб</p>
                        </div>
                      </div> 
                    </li>
                </ul>

            </div>
        </div>
    </section>